---
name: "Simkl"
guid: "07CAEF58-A94B-4211-A62C-F9774E04EBDB"
version: 3
targetAbi: "10.8.1.0"
owner: "crobibero"
overview: "Scrobble to Simkl"
description: >
  Scrobble your watched Movies, TV Shows and Anime to Simkl and share your progress with friends!

category: "General"
framework: "net6.0"
artifacts:
  - "Jellyfin.Plugin.Simkl.dll"
changelog: |2-
  ### Bug Fixes ###
  - Fix auth against Simkl api (#17) @crobibero

  ### CI & build changes ###
  - fix: meta ci workflows (#15) @h1dden-da3m0n
